[
    [
        '  printf("Enter the number: ");',
        '  scanf("%d", &num);',
        '  printf("The cube of number %d is %d", num, addComplexNum(num));',
    ],
    [
        '    printf("The cube of %d is %d\\n", i, i * i * i);',
        '  printf("Enter the number you want the cube till: ");',
        '  scanf("%d", &n);',
    ],
    [
        '  printf("Enter a number: ");',
        '  scanf("%d", &n);',
        '  printf("The number in octal form is: 0o%d", addComplexNum(n));',
    ],
    [
        '  printf("The sum of the two complex numbers is: %0.2f + %.2fi", real1 + real2, imaginary1 + imaginary2);',
        '  printf("Enter a complex number: ");',
        '  scanf("%f + %fi", &r1, &i1);',
        '  printf("Enter another complex number: ");',
        '  scanf("%f + %fi", &r2, &i2);',
    ],
    [
        '  printf("%d ", first);',
        '    printf("%d ", second);',
        '  printf("Enter a number n: ");',
        '  scanf("%d", &n);',
    ],
    [
        '        printf("%d + %d = %d\\n", i, j, n);',
        '  printf("Enter a number n: ");',
        '  scanf("%d", &n);',
    ],
    [
        '  printf("Enter an operator: ");',
        '  scanf("%c", &operator);',
        '  printf("Enter a number n1: ");',
        '  scanf("%f", &n1);',
        '  printf("Enter a number n1: ");',
        '  scanf("%f", &n2);',
        '    printf("Wrong operator");',
        '  printf("%f %c %f = %f", n1, operator, n2, result);',
    ],
    [
        '      printf("*");',
        '    printf("\\n");',
        '  printf("Enter a number of rows: ");',
        '  scanf("%d", &nRows);',
    ],
    [
        '    printf("%d ", n);',
        '  printf("%d", n);',
        '  printf("Enter any positive number N: ");',
        '  scanf("%d", &N);',
        '    printf("Number should be positive!");',
    ],
    [
        '  printf("Enter the size of the array: ");',
        '  scanf("%d", &size);',
        '    printf("Enter element %d: ", i + 1);',
        '    scanf("%d", &arr[i]);',
        "  puts(typeOfSequence(arr, size));",
        "this happens because when we doing 2.0 / 2000.0, even though its 0.001 mathematically, it gets stored as a value slightly larger than that...",
    ],
    ['  printf("%d", j);'],
    ['  printf("%d", n);', '  printf("%dn", fun(4, 1, 2, 3));'],
    ['  printf("a: %d, b: %d\\n", a, b);', '  printf("a: %d, b: %d", a, b);'],
    [
        '  printf("The value inside function is: %d\\n", *valuePtr);',
        '  printf("The value inside function is: %d\\n", value);',
        '  printf("The value of n before changeByValue: %d\\n", n);',
        '  printf("The value of n after changeByValue: %d\\n", n);',
        '  printf("\\n");',
        '  printf("The value of n before changeByReference: %d\\n", n);',
        '  printf("The value of n after changeByReference: %d\\n", n);',
    ],
    [
        '    printf("%f, %f, %0.15f\\n", i, j, i / j);',
        '    printf("%f\\n", sum);',
        '  printf("%d", count);',
    ],
]
