import json
import os
from qfluentwidgets import (
    QConfig,
    ConfigItem,
    OptionsConfigItem,
    BoolValidator,
    OptionsValidator,
    qconfig,
)

LANG_FILE = "./languages.json"


def load_languages():
    if os.path.exists(LANG_FILE):
        with open(LANG_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    return []  # fallback


languages_data = load_languages()
language_names = [lang["name"] for lang in languages_data] or ["C", "Python"]


class AppConfig(QConfig):
    language = OptionsConfigItem(
        "DOCX", "DefaultLanguage", "C", OptionsValidator(language_names)
    )
    pageBreak = ConfigItem("DOCX", "PageBreak", True, BoolValidator())
    heading = ConfigItem("DOCX", "Heading", "My Document")
    paragraph = ConfigItem("DOCX", "Paragraph", "Generated by save-code-x")

    # store the language list itself
    languages = ConfigItem("Lang", "Configs", languages_data)


cfg = AppConfig()
qconfig.load("config.json", cfg, autoSave=True)
