from qfluentwidgets import (
    QConfig,
    ConfigItem,
    OptionsConfigItem,
    BoolValidator,
    OptionsValidator,
    qconfig,
)

languages = ["C", "C++", "Python"]


class AppConfig(QConfig):
    # --- DOCX Settings ---
    language = OptionsConfigItem(
        "DOCX", "DefaultLanguage", "C", OptionsValidator(languages)
    )
    pageBreak = ConfigItem("DOCX", "PageBreak", True, BoolValidator())
    heading = ConfigItem("DOCX", "Heading", "My Document")
    paragraph = ConfigItem("DOCX", "Paragraph", "Generated by save-code-x")

    # --- Per-language configs ---
    languages = ConfigItem(
        "Lang",
        "Configs",
        [
            {
                "name": "C",
                "extension": ".c",
                "compile": "gcc $s.c -o $s",
                "run": "$s.exe",
                "input": "scanf, fgets, gets",
                "output": "printf, puts",
            },
            {
                "name": "C++",
                "extension": ".cpp",
                "compile": "g++ $s.cpp -o $s",
                "run": "$s.exe",
                "input": "cin, scanf, fgets, gets",
                "output": "cout, printf, puts",
            },
            {
                "name": "Python",
                "extension": ".py",
                "compile": "",
                "run": "python $s.py",
                "input": "input",
                "output": "print",
            },
        ],
    )


cfg = AppConfig()
qconfig.load("config.json", cfg, autoSave=True)
