import sys
import os
import json
from qfluentwidgets import (
    QConfig,
    ConfigItem,
    OptionsConfigItem,
    BoolValidator,
    OptionsValidator,
    qconfig,
)


def resource_path(relative_path):
    if hasattr(sys, "_MEIPASS"):
        return os.path.join(sys._MEIPASS, relative_path)
    return os.path.join(os.path.abspath("."), relative_path)


LANG_FILE = resource_path("languages.json")


def load_languages():
    if os.path.exists(LANG_FILE):
        with open(LANG_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    return []


languages_data = load_languages()
language_names = [lang["name"] for lang in languages_data] or ["C", "Python"]


class AppConfig(QConfig):
    language = OptionsConfigItem(
        "DOCX", "DefaultLanguage", "C", OptionsValidator(language_names)
    )
    pageBreak = ConfigItem("DOCX", "PageBreak", True, BoolValidator())
    heading = ConfigItem("DOCX", "Heading", "My Document")
    paragraph = ConfigItem("DOCX", "Paragraph", "Generated by save-code-x")
    languages = ConfigItem("Lang", "Configs", languages_data)
    openai_key = ConfigItem("API", "OpenAIKey", "", validator=None)


cfg = AppConfig()
qconfig.load("config.json", cfg, autoSave=True)
